app: "mediawiki"
replicacount: 1

mode: 0

port: 8080
nodeport: 0
nodepolicy: Cluster

image:
  registry: scr.dc.local:5443
  repository: is/mediawiki
  pullpolicy: "Always"

base:
  pki: "/usr/local/etc"
  var: "/var/opt/mediawiki"
  www: "/var/opt/nginx"
  sqlite: "/var/opt/sqlite"

envs: []
vols: []
mnts: []
