---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "common.labels.meta" . | indent 4 }}
spec:
  replicas: {{ .Values.replicacount }}
  selector:
    matchLabels:
{{ include "common.labels.match" . | indent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
{{ include "common.labels.meta" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Values.image.repository | trimPrefix "is/" }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.debug }}
          command: ["/bin/sh"]
          args: ["-c", "while true; do date; sleep 60; done"]
          {{- end }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: PROMETHEUS_OPTS
              value: "{{ .Values.opts }}"
          volumeMounts:
            - name: etc-{{ .Release.Name }}
              mountPath: /usr/local/etc/prometheus
              readOnly: true
            - name: var-{{ .Release.Name }}
              mountPath: /var/opt/prometheus
              readOnly: false
      volumes:
        - name: etc-{{ .Release.Name }}
          hostPath:
            path: {{ .Values.base.etc }}/{{ .Release.Name }}
            type: Directory
        - name: var-{{ .Release.Name }}
          hostPath:
            path: {{ .Values.base.var }}/{{ .Release.Name }}
            type: Directory
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: sa-prometheus
      automountServiceAccountToken: true
      enableServiceLinks: false
