app: "dovecot"
replicacount: 1
strategytype: Recreate

mode: 0

port: 143
portssl: 993
portlmtp: 24
nodeport: 0
nodeportssl: 0
nodeportlmtp: 0
nodepolicy: Cluster
loadbalancerip:

image:
  registry: scr.dc.local:5443
  repository: is/dovecot
  pullpolicy: "Always"

base:
  etc: "/usr/local/etc"
  var: "/var/opt/dovecot"

envs: []
vols: []
mnts: []
