---
apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Values.app }}
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  {{- if not .Values.nodeport }}
  type: ClusterIP
  {{- else }}
  type: NodePort
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Values.app }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      {{- if .Values.nodeport }}
      nodePort: {{ .Values.nodeport }}
      {{- end }}
