---
apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Release.Name }}
  labels:
{{ include "common.labels.meta" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
{{ include "common.labels.match" . | indent 4 }}
  ports:
    - name: pgsql
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
