---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "common.labels.meta" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "common.labels.match" . | indent 6 }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{ include "common.labels.meta" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Values.image.repository | trimPrefix "is/" }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.debug }}
          command: ["/bin/sh"]
          args: ["-c", "while true; do date; sleep 60; done"]
          {{- end }}
          {{- if .Values.hostport }}
          ports:
            - containerPort: {{ .Values.hostport }}
              hostPort: {{ .Values.hostport }}
          {{- end }}
          env:
            - name: NODE_EXPORTER_OPTS
              value: "{{ .Values.opts }}"
          volumeMounts:
            - name: host-root
              mountPath: /host
              mountPropagation: HostToContainer
              readOnly: true
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      automountServiceAccountToken: false
      enableServiceLinks: false
      hostNetwork: true
      hostPID: true
