app: "cgit"
replicacount: 1

debug: 0
port: 8080
nodeport: 0

image:
  registry: scr.dc.local:5443
  repository: is/cgit
  pullPolicy: "Always"

base:
  etc: "/usr/local/etc"
  www: "/var/opt/nginx"

envs:
  - name: NGINX_INIT
    value: "0"

vols: []
mnts: []
